name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |          
          PATH=~/perl5/bin"${PATH+:}${PATH}"
          export PERL5LIB=~/perl5/lib/perl5"${PERL5LIB+:}${PERL5LIB}"
          export PERL_LOCAL_LIB_ROOT=~/perl5"${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"
          export PERL_MB_OPT='--install_base "'~/perl5'"'
          export PERL_MM_OPT='INSTALL_BASE='~/perl5
          (
          echo '```sh'
          sudo apt-get install -y cpanminus
          x='Capture::Tiny Devel::Cover Devel::Cover::Report::Html Hash::Merge Module::Build::Tiny Text::Hunspell'
          echo $x | xargs perl /usr/bin/cpanm --verbose --notest
          cat ~/.bashrc || echo no bashrc
          for module in $x; do
            if perl -e "use $module; 1;" >&2; then
              echo ''
            else
              echo $? >&2
              echo $module
            fi
          done
          echo '```'
          ) | tee -a "$GITHUB_STEP_SUMMARY"
