name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get install -y cpanminus
          x='Capture::Tiny Devel::Cover Devel::Cover::Report::Html Hash::Merge Module::Build::Tiny Text::Hunspell'
          echo $x | xargs perl /usr/bin/cpanm --verbose --notest
          for module in $x; do
            if perl -e "use $module; 1;" >&2; then
              echo ''
            else
              echo $? >&2
              echo $module
            fi
          done
